// <auto-generated />
using coreSQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace coreSQLite.Migrations
{
    [DbContext(typeof(FPContext))]
    [Migration("20180630094106_PrimaVersione")]
    partial class PrimaVersione
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("coreSQLite.Dati", b =>
                {
                    b.Property<int>("DatiId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("categoria");

                    b.Property<string>("datati");

                    b.Property<string>("descrizione");

                    b.Property<string>("importo");

                    b.Property<string>("nome");

                    b.HasKey("DatiId");

                    b.ToTable("Datis");
                });

            modelBuilder.Entity("coreSQLite.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("password");

                    b.Property<string>("utente");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("coreSQLite.UserLog", b =>
                {
                    b.Property<int>("UserLogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("utentelog");

                    b.HasKey("UserLogId");

                    b.ToTable("UserLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
